import requests
import streamlit as st


class UI:
    """
    A class to handle the Streamlit user interface for the application.
    """

    def __init__(self):
        pass

    def _get_api_response(self, user_input: str) -> dict:
        """
        Get the API response for the user's input.

        Args:
            user_input: The user's input.

        Returns:
            The API response.
        """
        response = requests.post(
            "http://localhost:8000/formalize", json={"text": user_input}
        )
        return response.json()

    def _send_feedback(self, user_input, api_output, feedback):
        """
        Send feedback to the API.

        Args:
            input: The user's input.
            output: The output generated by the API.
            feedback: The user's feedback.
        """
        pass

    def show_main_page(self):
        """
        Display the main page of the application.
        """
        st.title("Formalizacja tekstu 🌐️")

        with st.form(key="formalizer_form"):
            user_input = st.text_area(
                "Wpisz treść do sformalizowania",
                st.session_state.get("input_text", ""),
                height=100,
                max_chars=1000,
            )

            col1, col2 = st.columns(2)
            with col1:
                submit = st.form_submit_button("Sformalizuj")
            with col2:
                clear = st.form_submit_button("Wyczyść")

        if clear:
            st.session_state.input_text = ""
            st.session_state.formalized_text = ""
            st.session_state.feedback_message = None
            st.rerun()

        if submit and user_input:
            response = self._get_api_response(user_input)
            st.session_state.input_text = user_input
            st.session_state.formalized_text = response["formalized_text"]
            st.session_state.feedback_message = None
            st.rerun()

        if st.session_state.get("formalized_text"):
            st.text_area(
                label="Sformalizowany tekst:",
                value=st.session_state.formalized_text,
                height=100,
            )

            col1, col2 = st.columns(2)
            with col1:
                if st.button("👍 Podoba mi się", key="like"):
                    self._send_feedback(
                        st.session_state.input_text,
                        st.session_state.formalized_text,
                        "positive",
                    )
                    st.session_state.feedback_message = "positive"
                    st.rerun()
            with col2:
                if st.button("👎 Nie podoba mi się", key="dislike"):
                    self._send_feedback(
                        st.session_state.input_text,
                        st.session_state.formalized_text,
                        "negative",
                    )
                    st.session_state.feedback_message = "negative"
                    st.rerun()

            if st.session_state.get("feedback_message") == "positive":
                st.success("Dziękujemy za opinię!")
            elif st.session_state.get("feedback_message") == "negative":
                st.error(
                    "Dziękujemy za opinię! Twoja opinia pomoże nam poprawić jakość usługi."
                )

    def main(self):
        self.show_main_page()


if __name__ == "__main__":
    ui = UI()
    ui.main()
